### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/all-my-sms#1]
- [x] Code Review
- [x] Add @mikaelpopowicz as repo admin
- [x] Add @mikaelpopowicz to github org
- [x] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by atymic** [comment]
Website PR here
https://github.com/laravel-notification-channels/website/pull/9/files

**Comment by atymic** [comment]
Looks like we are good to go. Tag the first release when you are ready, and I'll merge the website PR :)

**Comment by mikaelpopowicz** [comment]
First tag added.

**Comment by atymic** [comment]
Sweet! Website PR has been merged. 
Channel is live 🎉
